In [51]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [52]:
df = pd.read_csv('breast-cancer.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [53]:
df.shape

(569, 32)

In [54]:
df.drop(columns=['id'],inplace=True)

In [55]:
df.shape

(569, 31)

In [56]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

#### Train_test_split

In [57]:
X_train, X_test, y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [58]:
X_train.shape

(455, 30)

In [59]:
y_test # Target: M - Malignant B - Benign

501    M
54     M
348    B
119    M
89     B
      ..
374    B
399    B
544    B
156    M
549    B
Name: diagnosis, Length: 114, dtype: str

#### Scaling

In [60]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [61]:
X_train

array([[-0.66858227, -0.42419129, -0.69703058, ..., -0.35140518,
         0.36423963, -0.7331695 ],
       [-0.60637788, -1.34142534, -0.60309675, ..., -0.61630544,
        -0.16459139, -0.16204931],
       [-0.82692073, -1.43269241, -0.83280394, ..., -0.41054147,
        -0.24391604, -0.17844511],
       ...,
       [ 0.57267814, -0.12529163,  0.66726601, ...,  0.88894064,
        -0.18276996,  1.246896  ],
       [-0.48762404, -0.56337357, -0.54731072, ..., -1.31517511,
        -1.59243513, -1.18842608],
       [-0.57244821, -1.37565049, -0.55182283, ..., -0.49591001,
         0.97239529,  0.4877707 ]], shape=(455, 30))

In [62]:
y_train

293    B
529    B
271    B
454    B
466    B
      ..
423    B
543    B
283    M
315    B
130    B
Name: diagnosis, Length: 455, dtype: str

#### Label Encoding
* m aur b humera model nahi samajh sakta hai isiliya hum label incoding ker reha hai

In [63]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [64]:
y_train

array([0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0])

### Numpy array to pytorch tensor

In [65]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()

y_train_tensor = torch.from_numpy(y_train).float().view(-1, 1)
y_test_tensor = torch.from_numpy(y_test).float().view(-1, 1)

In [66]:
X_train_tensor.dtype

torch.float32

In [67]:
X_train_tensor.shape

torch.Size([455, 30])

##### conclusion --> our deep learning model work on tensor

In [68]:
# our model have 30 weights and 1 bias
class MySimpleNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)

        return out

#### Important Parameters

In [69]:
learning_rate = 0.1
epochs = 25

In [70]:
# Define loss function
loss_function = nn.BCELoss()

#### Training pipeline

In [71]:
# crate model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):
    
    # forward pass
    y_pred = model(X_train_tensor)
    # loss calculate
    loss = loss_function(y_pred, y_train_tensor)
    # clear gradients
    optimizer.zero_grad()
    # backword pass
    loss.backward()
    # parameter updations
    optimizer.step()

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, loss: {loss.item()}')

Epoch: 1, loss: 0.5691523551940918
Epoch: 2, loss: 0.45865538716316223
Epoch: 3, loss: 0.39560970664024353
Epoch: 4, loss: 0.35416215658187866
Epoch: 5, loss: 0.3242691457271576
Epoch: 6, loss: 0.3013785183429718
Epoch: 7, loss: 0.2831122875213623
Epoch: 8, loss: 0.26809120178222656
Epoch: 9, loss: 0.255452424287796
Epoch: 10, loss: 0.24462437629699707
Epoch: 11, loss: 0.2352113127708435
Epoch: 12, loss: 0.2269294559955597
Epoch: 13, loss: 0.21956920623779297
Epoch: 14, loss: 0.2129719853401184
Epoch: 15, loss: 0.20701521635055542
Epoch: 16, loss: 0.20160244405269623
Epoch: 17, loss: 0.19665662944316864
Epoch: 18, loss: 0.19211526215076447
Epoch: 19, loss: 0.18792709708213806
Epoch: 20, loss: 0.1840496063232422
Epoch: 21, loss: 0.18044714629650116
Epoch: 22, loss: 0.17708958685398102
Epoch: 23, loss: 0.17395120859146118
Epoch: 24, loss: 0.17100992798805237
Epoch: 25, loss: 0.16824667155742645

* grad.zero_() is an in-place PyTorch method that resets the accumulated gradients of a specific tensor to zero, ensuring that subsequent backward() passes compute fresh gradients for the current batch rather than adding to previous values.

In [72]:
model.linear.bias

Parameter containing:
tensor([-0.0861], requires_grad=True)

#### Evaluation

In [74]:
# model evaluation
with torch.no_grad(): # no_grad mean hum ko abhi koi backword propagation nahi kerna hai isiliya hum no grad ker reha hai
    y_pred = model(X_test_tensor)
    y_pred = (y_pred > 0.5).float() # means less than 0.5 --> and greater then 0.5 -> 1
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.9649122953414917