In [121]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [122]:
df = pd.read_csv('breast-cancer.csv')
df.head()

         id diagnosis  ...  symmetry_worst  fractal_dimension_worst
0    842302         M  ...          0.4601                  0.11890
1    842517         M  ...          0.2750                  0.08902
2  84300903         M  ...          0.3613                  0.08758
3  84348301         M  ...          0.6638                  0.17300
4  84358402         M  ...          0.2364                  0.07678

[5 rows x 32 columns]

In [123]:
df.shape

(569, 32)

In [124]:
df.drop(columns=['id'],inplace=True)

In [125]:
df.shape

(569, 31)

In [126]:
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

#### Train_test_split

In [127]:
X_train, X_test, y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [128]:
X_train.shape

(455, 30)

In [129]:
y_test # Target: M - Malignant B - Benign

45     M
362    B
206    B
35     M
379    M
      ..
142    B
370    M
292    B
312    B
48     B
Name: diagnosis, Length: 114, dtype: str

#### Scaling

In [130]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [131]:
X_train

array([[ 1.2685213 ,  0.57181579,  1.24631825, ...,  0.83923096,
         0.19692195, -0.04441067],
       [ 2.06420623, -0.48816624,  1.93389631, ...,  1.00841609,
        -0.60271433, -1.03732282],
       [-0.32560182, -0.22541646, -0.39627374, ..., -0.98358777,
        -1.4441827 , -1.21462856],
       ...,
       [-1.25123945, -0.29727965, -1.25774509, ..., -1.36319691,
         0.27736826, -0.28390981],
       [-0.5596268 ,  0.24618571, -0.61174152, ..., -0.61832916,
        -0.30667193, -0.82782926],
       [ 1.46400099,  2.92982666,  1.41821277, ...,  0.71385269,
        -0.27610233, -0.45139554]], shape=(455, 30))

In [132]:
y_train

433    M
368    M
37     B
16     M
299    B
      ..
105    M
515    B
467    B
102    B
219    M
Name: diagnosis, Length: 455, dtype: str

#### Label Encoding
* m aur b humera model nahi samajh sakta hai isiliya hum label incoding ker reha hai

In [133]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [134]:
y_train

array([1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1])

### Numpy array to pytorch tensor

In [135]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor  = torch.from_numpy(X_test)

y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [136]:
X_train_tensor.dtype

torch.float64

In [137]:
X_train_tensor.shape

torch.Size([455, 30])

##### conclusion --> our deep learning model work on tensor

In [138]:
# our model have 30 weights and 1 bias
class MySimpleNN():
    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.rand(1, dtype=torch.float64, requires_grad=True)

    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    # loss function
    def loss_function(self, y_pred, y):
        # clamp prediction to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
        # calculate loss
        loss = -(y_train_tensor + torch.log(y_pred) + (1 - y_train_tensor) + torch.log(1 - y_pred)).mean()
        return loss

#### Important Parameters

In [139]:
learning_rate = 0.1
epochs = 25

#### Training pipeline

In [141]:
# crate model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):
    
    # forward pass
    y_pred = model.forward(X_train_tensor)
    # loss calculate
    loss = model.loss_function(y_pred, y_train_tensor)
    
    # backword pass
    loss.backward()
    # parameter updations
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, loss: {loss.item()}')

Epoch: 1, loss: 6.547693667665146
Epoch: 2, loss: 5.992863470802679
Epoch: 3, loss: 5.4131155647334275
Epoch: 4, loss: 4.806014282052755
Epoch: 5, loss: 4.16874790912057
Epoch: 6, loss: 3.520550459848893
Epoch: 7, loss: 2.8700376172836584
Epoch: 8, loss: 2.2640444664331145
Epoch: 9, loss: 1.7189774803011426
Epoch: 10, loss: 1.2728215942807173
Epoch: 11, loss: 0.9674246974725889
Epoch: 12, loss: 0.7894949938413819
Epoch: 13, loss: 0.6979090187836159
Epoch: 14, loss: 0.6496016415388302
Epoch: 15, loss: 0.6193712753269103
Epoch: 16, loss: 0.5969173654648326
Epoch: 17, loss: 0.5785746548252454
Epoch: 18, loss: 0.5629627897685626
Epoch: 19, loss: 0.5494383714388125
Epoch: 20, loss: 0.537614485734142
Epoch: 21, loss: 0.5272143311077944
Epoch: 22, loss: 0.5180223531723487
Epoch: 23, loss: 0.5098640118552111
Epoch: 24, loss: 0.5025949560586015
Epoch: 25, loss: 0.4960941238444439

* grad.zero_() is an in-place PyTorch method that resets the accumulated gradients of a specific tensor to zero, ensuring that subsequent backward() passes compute fresh gradients for the current batch rather than adding to previous values.

In [142]:
model.bias

tensor([0.1924], dtype=torch.float64, requires_grad=True)

In [143]:
#### Evaluation

In [149]:
# model evaluation
with torch.no_grad(): # no_grad mean hum ko abhi koi backword propagation nahi kerna hai isiliya hum no grad ker reha hai
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float() # means less than 0.5 --> and greater then 0.5 -> 1
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.4833795130252838